# Generated by Django 2.1.15 on 2020-05-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20200516_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='category',
            field=models.CharField(choices=[('', '--'), ('A', 'admin'), ('B', 'user1'), ('C', 'C'), ('D', 'D')], max_length=32, verbose_name='Category'),
        ),
    ]
